// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfQ-EaSxeGQmUulx9TKd4qFUXG6JU9dP4',
    appId: '1:780025051674:web:72b4770d9555878084efa3',
    messagingSenderId: '780025051674',
    projectId: 'hostel-management-system-2b04c',
    authDomain: 'hostel-management-system-2b04c.firebaseapp.com',
    storageBucket: 'hostel-management-system-2b04c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDzFlb9oAqnrd-syaA8FMp8mW8xbudbZ8',
    appId: '1:780025051674:android:b91dd04920043b5884efa3',
    messagingSenderId: '780025051674',
    projectId: 'hostel-management-system-2b04c',
    storageBucket: 'hostel-management-system-2b04c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV66OuqfHwd5rj8IFdIFd2eWpCSpO__EE',
    appId: '1:780025051674:ios:a17383e365ed330284efa3',
    messagingSenderId: '780025051674',
    projectId: 'hostel-management-system-2b04c',
    storageBucket: 'hostel-management-system-2b04c.firebasestorage.app',
    iosBundleId: 'com.example.hms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV66OuqfHwd5rj8IFdIFd2eWpCSpO__EE',
    appId: '1:780025051674:ios:a17383e365ed330284efa3',
    messagingSenderId: '780025051674',
    projectId: 'hostel-management-system-2b04c',
    storageBucket: 'hostel-management-system-2b04c.firebasestorage.app',
    iosBundleId: 'com.example.hms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfQ-EaSxeGQmUulx9TKd4qFUXG6JU9dP4',
    appId: '1:780025051674:web:b0043355f37272e884efa3',
    messagingSenderId: '780025051674',
    projectId: 'hostel-management-system-2b04c',
    authDomain: 'hostel-management-system-2b04c.firebaseapp.com',
    storageBucket: 'hostel-management-system-2b04c.firebasestorage.app',
  );
}
